package com.test.web.models;
// Generated Oct 14, 2019 8:19:17 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;


import java.util.List;

import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "category", catalog = "hbtest")
public class Category extends Base implements java.io.Serializable {


	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	//private Integer id;
	private String name;
	
	List<Product> products;

	public Category() {
	}

	public Category(String name) {
		this.name = name;
	}

	
	@Column(name = "name", length = 60)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	@OneToMany(mappedBy = "category", cascade = CascadeType.ALL)
	public List<Product> getProducts() {
		return products;
	}
	
	public void setProducts(List<Product> products) {
		this.products = products;
	}

}
