package com.test.web.models;
// Generated Oct 14, 2019 8:19:17 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;


import java.util.List;

import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "country", catalog = "hbtest")
public class Country extends Base implements java.io.Serializable {


	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String code;
	private String name;
	
	List<State> states;

	public Country() {
	}

	public Country(String code, 
			String name) {
		this.code = code;
		this.name = name;
	}

	
	@Column(name = "name", length = 60)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	@OneToMany(mappedBy = "country", cascade = CascadeType.ALL)
	public List<State> getStates() {
		return states;
	}
	
	public void setStates(List<State> states) {
		this.states = states;
	}

	@Column(name = "code", length = 3)
	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

}
