package com.test.web.models;
// Generated Oct 14, 2019 8:19:17 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;

import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "hbtest")
public class Product extends Base implements java.io.Serializable {



	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;


	private String name;

	
	private Category category;

	public Product() {
	}

	public Product(int id, String name, Category category) {
		super.setId(id);
		this.name = name;
		this.category = category;
	
	}

	@Column(name = "name", length = 60)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	

	@ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "categoryId")
	public Category getCategory() {
		return category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

}
