package com.test.web.models;
// Generated Oct 14, 2019 8:19:17 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.ManyToMany;

import java.util.List;

import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "role", catalog = "hbtest")
public class Role extends Base implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * 
	 */

	//private Integer id;
	private String name;
	
	List<User> users;

	public Role() {
	}

	public Role(String name) {
		this.name = name;
	}
	
	public Role(int id) {
		setId(id);
	}


	@Column(name = "name", length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	

	@ManyToMany(mappedBy = "roles")
	public List<User> getUsers() {
		return users;
	}
	
	public void setUsers(List<User> users) {
		this.users = users;
	}

}
