package com.test.web.models;
// Generated Oct 14, 2019 8:19:17 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;

import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "state", catalog = "hbtest")
public class State extends Base implements java.io.Serializable {



	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String code;
	private String name;

	
	private Country country;

	public State() {
	}

	public State(int id, String name, Country country) {
		super.setId(id);
		this.name = name;
		this.country = country;
	
	}

	@Column(name = "name", length = 60)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	

	@ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "countryId")
	public Country getCountry() {
		return country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	@Column(name = "code", length = 3)
	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

}
